version: '3.8'
services:
  r:
    image: rocker/verse
    ports:
      - '8787:8787'
    volumes: 
      -  .:/home/rstudio/manuscript
    environment: 
      DISABLE_AUTH: 'true'
    command: ./home/rstudio/manuscript/compile.sh
